### ISSUE TITLE
代码中使用filter实现信号在信道中的传输有理论参考吗？

### ISSUE THREAD

**Issue by jianjianliu0918** [axiomaster/lism_final_paper#1]
y_faded = filter(chan,reshape(x_tr,N*L,1)); 这部分不太清楚，请问有相关的资料参考吗？感谢解答

**Comment by axiomaster** [comment]
有一本matlab开发经理写的关于matlab在4G LTE仿真方面应用的书，具体书名忘记了。
这本书有对应中文版，可以看一下。
我们当时就是参考这本书开发的链路方针代码。

**Comment by jianjianliu0918** [comment]
> 有一本matlab开发经理写的关于matlab在4G LTE仿真方面应用的书，具体书名忘记了。
> 这本书有对应中文版，可以看一下。
> 我们当时就是参考这本书开发的链路方针代码。

**Comment by jianjianliu0918** [comment]
> 有一本matlab开发经理写的关于matlab在4G LTE仿真方面应用的书，具体书名忘记了。
> 这本书有对应中文版，可以看一下。
> 我们当时就是参考这本书开发的链路方针代码。

感谢回复，刚找了一下，书名是《Understanding LTE with MATLAB: from mathematical modeling to simulation and prototyping》

**Comment by axiomaster** [comment]
嗯嗯，就是这本书。这本书也有对应的中文版
